create index if not exists idx_buildings_project_id on buildings(project_id);
create index if not exists idx_projects_company_id on projects(company_id);
create index if not exists idx_profiles_company_id on profiles(company_id);
create index if not exists idx_elements_building_id on elements(building_id);
create index if not exists idx_elements_created_by on elements(created_by);
create index if not exists idx_deliveries_created_by on deliveries(created_by);
create index if not exists idx_delivery_items_delivery_id on delivery_items(delivery_id);
create index if not exists idx_delivery_items_element_id on delivery_items(element_id);
create index if not exists idx_delivery_items_loaded_by on delivery_items(loaded_by);
create index if not exists idx_element_events_created_by on element_events(created_by);
create index if not exists idx_element_photos_taken_by on element_photos(taken_by);
create index if not exists idx_element_positions_floor_plan_id on element_positions(floor_plan_id);
create index if not exists idx_floor_plans_project_id on floor_plans(project_id);
create index if not exists idx_floor_plans_building_id on floor_plans(building_id);
create index if not exists idx_floor_plans_previous_version_id on floor_plans(previous_version_id);
create index if not exists idx_floor_plans_uploaded_by on floor_plans(uploaded_by);
create index if not exists idx_project_documents_project_id on project_documents(project_id);
create index if not exists idx_project_documents_uploaded_by on project_documents(uploaded_by);
create index if not exists idx_diary_entries_user_id on diary_entries(user_id);
create index if not exists idx_diary_entries_project_id on diary_entries(project_id);
create index if not exists idx_todo_items_user_id on todo_items(user_id);
create index if not exists idx_todo_items_project_id on todo_items(project_id);
create index if not exists idx_supplier_items_supplier_id on supplier_items(supplier_id);
create index if not exists idx_stock_items_supplier_item_id on stock_items(supplier_item_id);

create index if not exists idx_elements_project_status on elements(project_id, status);
create index if not exists idx_elements_project_priority on elements(project_id, priority desc, created_at);
create index if not exists idx_deliveries_project_date on deliveries(project_id, planned_date);
create index if not exists idx_deliveries_driver_status on deliveries(driver_id, status);
create index if not exists idx_todo_items_user_complete on todo_items(user_id, is_completed, due_date);
